// chargebee-js-react/src/components/Element.jsx
import React from 'react';
import { isEqual, genUUID } from '../utils/';

export default class Element extends React.Component {
    constructor(props) {
        super(props);
        this.field = null
        this.id = `card-${props.type}-${genUUID()}`;
        this.ElementRef = React.createRef();
    }

    componentDidMount() {
        const { cbComponent, type, listeners } = this.props;
        const options = this.getPropOptions(this.props);
        this.field = cbComponent.createField(type, options).at(`#${this.id}`);
        
        // Attaching listeners if any
        if(listeners) {
            if(listeners.onBlur) this.field.on('blur', listeners.onBlur);
            if(listeners.onFocus) this.field.on('focus', listeners.onFocus);
            if(listeners.onReady) this.field.on('ready', listeners.onReady);
            if(listeners.onChange) this.field.on('change', listeners.onChange);
        }
    }

    getPropOptions(props) {
        const { icon, styles: style, placeholder } = props;
        return {
            icon,
            style,
            placeholder,
        }
    }

    componentDidUpdate(prevProps) {
        const prevOptions = this.getPropOptions(prevProps)
        const currentOptions = this.getPropOptions(this.props)

        if(!isEqual(prevOptions, currentOptions) && this.field) {
            this.field.update(currentOptions)
        }
    }

    componentWillUnmount() {
        this.field.destroy();
    }

    focus() {
        this.field.focus();
    }

    blur() {
        this.field.blur();
    }

    clear() {
        this.field.clear();
    }

    render() {
        const {className} = this.props;
        return (
            <div id={this.id} ref={this.ElementRef} className={className}>
                {this.props.children}
            </div>
        )
    }
}

// chargebee-js-vue/src/components/Element.vue
<script>
import { genUUID } from '../utils';
export default {

  data () {
    return {
      field: null
    }
  },

  props: {
    styles: {
      type: Object,
      default: () => ({})
    },
    placeholder: {
      type: String,
      default: () => ''
    },
  },

  computed: {
    fieldOptions: function() {
      return {
        style: this.styles || {},
        placeholder: this.placeholder
      }
    },

    elementId: function() {
      return `card-${this.id}-${genUUID()}`
    }
  },

  methods: {
    getField () {
      return this.field
    },

    attachListener (listener) {
      this.field.on(listener, (data) => {
        this.$emit(listener, data)
      })
    },

    initializeField (cbComponent) {
      if (cbComponent) {
        const options = this.fieldOptions;
        this.field = cbComponent.createField(this.id, options).at(`#${this.elementId}`)
        if (this.$parent.onMount) this.$parent.onMount()

        // Attach listeners if any
        this.attachListener('ready')
        this.attachListener('focus')
        this.attachListener('blur')
        this.attachListener('change')
      }
    },

    focus() {
      this.field.focus();
    },

    blur() {
      this.field.blur();
    },

    clear() {
      this.field.clear();
    },
    
  },

  watch: {
    cbComponent: function (cbComponent, _) {
      if (!this.field) {
        this.initializeField(cbComponent)
      }
    },

    fieldOptions: function () {
      if(this.field) {
        const options = this.fieldOptions;
        this.field.update(options)
      }
    },
  },

  mounted () {
    this.initializeField(this.cbComponent)
  }
}
</script>
