// chargebee-js-react/src/components/Provider.jsx
import React from 'react';
import { validateCbInstance } from '../utils/';


export default React.forwardRef((props, ref) => {
    if (props.cbInstance && validateCbInstance(props.cbInstance)) {
        return (
            <>
                {props.children}
            </>
        );
    } else {
        return null;
    }  
});

// chargebee-js-vue/src/components/Provider.vue
<script lang="ts">
import { validateCbInstance } from '../utils'

export default {
    name: 'Provider',
    props: {
        cbInstance: {
            type: Object,
            default: null
        },
    },
    render() {
        if (validateCbInstance(this.cbInstance))
            return this.$slots.default();
        else
            return null;
    }
}
</script>
