// chargebee-js-react/src/components/Provider.tsx
import * as React from 'react';
import { ChargebeeInstance } from '@chargebee/chargebee-js-types';
import { validateCbInstance } from '../utils/';

interface ProviderProps {
    cbInstance: ChargebeeInstance;
    children: React.ReactChild;
}

export default React.forwardRef((props: ProviderProps, ref) => {
    if (props.cbInstance && validateCbInstance(props.cbInstance)) {
        return (
            <>
                {props.children}
            </>
        );
    } else {
        return null;
    }  
});

// chargebee-js-vue/src/components/Provider.vue
<script lang="ts">
import { PropType } from 'vue';
import { ChargebeeInstance } from '@chargebee/chargebee-js-types';
import { validateCbInstance } from '../utils/';

export default {
    name: 'Provider',
    props: {
        cbInstance: {
            type: Object as PropType<ChargebeeInstance>,
            default: null
        },
    },
    render() {
        if (validateCbInstance(this.cbInstance))
            return this.$slots.default();
        else
            return null;
    }
}
</script>
